дадано розмітку та стилі
Volodymyr-Zastavniuk/team-project-icecream pull request #2
Opened 2022-08-11 10:27 UTC by KychataOlena

дадано розмітку та стилі без іконок

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk requested changes

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +@import '../utils/mixins';
этот импорт можно удалить

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +
добавь место для иконок .advantages__item  {padding top 66px}    /   86px (tablet up)   /  90px (desktop up)

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  display: flex;
перенеси  display: flex;  в tablet up
можно убрать flex-direction: column;

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +    flex-direction: row;
теперь direction row тоже можно убрать

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +    flex-direction: row;
и тут row не нужен

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +    column-gap: 22px;
можно просто gap поставить

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +     column-gap: 80px;
можно просто gap поставить

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
>    background-color: var(--bg-fifth-color);
--bg-secondary-color   замени цвет фона

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  .advantages__text--mobile{
удали этот модификатор и маржин, они не нужны

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +
добавь max-width 230px

2022-08-11 21:23 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  line-height: 1.13;
добавь font-weight 400

2022-08-12 18:43 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +@import '../utils/mixins';
видалила

2022-08-12 18:43 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +
додала іконку

2022-08-12 18:43 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +  display: flex;
видалила

2022-08-12 18:43 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +    flex-direction: row;
видалила

2022-08-12 18:43 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +    flex-direction: row;
+

2022-08-12 18:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +     column-gap: 80px;
зробила

2022-08-12 18:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
>    background-color: var(--bg-fifth-color);
зробила

2022-08-12 18:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +  .advantages__text--mobile{
зробила

2022-08-12 18:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +
зробила

2022-08-12 18:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +  line-height: 1.13;
зробила

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk requested changes

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  margin-bottom: 25px;
тут вроде 16пх отступ в макете

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/partials/advantages.html
> +        <svg class="advantades__icon" width="33" height="50">
ставь их все 50 х 50, очень маленькие на мобильном выходят, меньше чем на макете

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/partials/advantages.html
> +        <svg class="advantades__icon" width="33" height="50">
и тут 50 х 50

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/partials/advantages.html
> +        <svg class="advantades__icon advantades__icon--heart" width="33" height="50">
и тут 50 х 50

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +    margin-bottom: 55px;
тут 40пх

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +    margin-bottom: 41px;
тут маржин 36пх и width i height можно убрать

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  outline: 1px solid tomato;
outline не забудь убрать

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  padding-bottom: 120px;
тут паддинг топ 40пх

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +    margin-bottom: 22px;
маржин боттом 15пх

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +      margin-bottom: 28px;
маржин боттом 14пх

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  margin-bottom: 29px;
маржин боттом 19пх

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +  gap: 32px;
тут все таки нужен flex-direction: column; иначе на 750пх перепрыгивает во вторую колонку.  Возвращай назад )

2022-08-12 23:29 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_advantages.scss
> +    display: flex;
а тут тогда flex-direction: row

2022-08-13 12:34 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +    column-gap: 22px;
зробила

2022-08-13 12:34 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +  outline: 1px solid tomato;
прибрала

2022-08-13 12:41 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +  margin-bottom: 25px;
25х я міряла, але я поставлю 16 перевіриш

2022-08-13 12:42 UTC, KychataOlena commented on src/partials/advantages.html
> +        <svg class="advantades__icon" width="33" height="50">
додала

2022-08-13 12:43 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +  margin-bottom: 29px;
+

2022-08-13 12:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +      margin-bottom: 28px;
+

2022-08-13 12:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +    margin-bottom: 22px;
+

2022-08-13 12:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +  gap: 32px;
є

2022-08-13 12:44 UTC, KychataOlena commented on src/sass/sections/_advantages.scss
> +    display: flex;
є

2022-08-13 13:15 UTC, merged