стилі для кнопок
Volodymyr-Zastavniuk/team-project-icecream pull request #3
Opened 2022-08-11 11:44 UTC by KychataOlena

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk requested changes

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +@import'../utils/mixins';
этот import можно удалить

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
>  .button {
тут боковые паддинги 35px я пропустил, нужно добавить и вместо line height написать height, а line height можно по проекту посчитать

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +.button-modal__menu {
эта кнопка не нужна, она дублирует первую можно применить первую

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +  padding: 11px 24px;
тут изменить/добавить
padding 0px 14px
line-height 24px
border none
cursor pointer

@for desktop:
padding 0px 20px  
line-height 40px
min-width 107px

hover + focus добавить

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +.hero-button__products{
класс например .btn-small

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +.hero-button__hsmade{
тут удалить и сделать копию btn-small и это будет класс-модификатор .btn-small--white и просто заменить цвета, ховер фокус тоже цвета поменять

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +.button-location{
тут удалить и сделать копию button и это будет класс-модификатор .button-red и просто заменить цвета, ховер фокус тоже цвета поменять

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +.button-franchise{
эту удалить

2022-08-11 19:27 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +@import'../utils/mixins';
Общая идея по кнопкам. Это сделать две кнопки (большую и маленькую). Потом 2 модификатора (изменить цвет на красный/белый). И применять всего 4 кнопки в проекте.

2022-08-11 19:38 UTC, KychataOlena commented
Володимир, можеш цю гілку замержати, щоб я далі працювала з нею?

2022-08-11 19:41 UTC, Volodymyr-Zastavniuk commented
если мерж сделать пропадут примечания. Она не открывается у тебя?

2022-08-11 19:47 UTC, KychataOlena commented
все, зрозуміла, сорі

2022-08-12 12:44 UTC, Volodymyr-Zastavniuk requested changes

2022-08-12 12:44 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +    padding: 9px 15px;
тут padding: 7px 14px;

2022-08-12 12:44 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +      padding: 15px 26px;
а тут  padding: 11px 21px;

2022-08-12 12:44 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +fill: var(--text-secondary-color);
тут --accent-color

2022-08-12 12:44 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
>  .button--white{
эти стили и ховер перекинь в просто Button, она будет белая по умолчанию, а красная правильно с модификаторм --red.   Для белой не нуден модификатор, это будет по умолчанию кнопка )

2022-08-12 12:44 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +    background: linear-gradient(to right, #b91d73, #f953c6);
Постарайся для градиента выбрать цвета из макета, а то эти очень сильно выбиваются из дизайна

2022-08-12 13:07 UTC, KychataOlena commented on src/sass/components/_button.scss
> +    background: linear-gradient(to right, #b91d73, #f953c6);
якщо брати колір з макету ховер майже не видно, ці ніби цікавіші, можливо подивимось вже на готовму варіанті +-, якщо будуть погані тоді зроблю заміну на ті що в макеті. 
ми ж можемо змінювати трхи стилі)
погоджуєшся?

2022-08-12 15:25 UTC, Volodymyr-Zastavniuk requested changes

2022-08-12 15:25 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +    background: var(--btn-red-hover-bg-color);
туу давай пока как на макете поставим серый фон, а то этот фон сливается с секцией :(  
    background: var(--btn-hover-bg-color);
    color: var(--accent-color);

2022-08-12 15:25 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
> +  &:focus &__icon {
этот fill  пока уберем или закомментируй

2022-08-12 15:25 UTC, Volodymyr-Zastavniuk commented on src/sass/components/_button.scss
>          &:focus {
этот ховер/фокус пока тоже закомментируй, пока пусть кнопки будут как на макете, я закину в мейн

2022-08-12 21:21 UTC, Volodymyr-Zastavniuk approved these changes

2022-08-12 21:22 UTC, merged