adds markup and style
Volodymyr-Zastavniuk/team-project-icecream pull request #4
Opened 2022-08-11 12:28 UTC by Ayzen-Olha

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk requested changes

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  margin-bottom: 8px;
маржин-боттом 148 для мобилки лучше поставить (размер до секции) так как картинки абсолютно позиционируются и все поедет.

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    margin-top: 18px;
замени миксин на for tablet up  и маржин топ 18 и маржин боттом 158. Плюс размер текста пропустила

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  @include for-tablet-up {
можно удалить

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  @include for-desktop-up {
тут добавить маржин боттом 281 (до секции расстояние) и тут размер текста тоже надо добавить как в проекте

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    display: flex;
добавь gap 16px

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    margin: -16px;
маржин удали лучше просто gap 32px поставь

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  @include for-tablet-up {
этот миксин и маржин удалить, (мы вверху просто gap сделали)

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    margin: 16px;
этот миксин и маржин удалить, (мы вверху просто gap сделали)

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +
добавь миксин for-phone-only 
&:not(:first-child)
маржин-топ 140пх (это отступы между карточками на мобильном без учета картинок)

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  background-color: var(--btn-red-hover-bg-color);
--bg-third-color  то цвет для ховера. лучше на эту переменную поменять

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  width: 40px;
пропустила border none

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  margin-bottom: 70px;
тут тоже размер текста для разных версий добавь

2022-08-11 20:34 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +  padding-top: 20px;
padding top 160px /   118 (tablet)  / 165 (desktop)
и остальные паддинги (по бокам и снизу пропиши сразу, они там разные)

2022-08-12 10:25 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    display: flex;
fixed. 
Change lines: 74-81 
@include for-tablet-up {
    display: flex;
    margin: 8px;
  } 
@include for-desktop-up {
    margin: -16px;
  }

and Change lines: 115-122 
@include for-tablet-up {
      margin: 8px;
    }
    @include for-desktop-up {
      margin: 16px;
      padding-top: 165px;
    }

так працює. і not last child видалила для таблетки

2022-08-12 10:25 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +
fixed
зробила через 
@include for-phone-only {
    display: flex;
    flex-direction: column;
    gap: 140px;
  }

2022-08-12 10:25 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +  @include for-tablet-up {
done

2022-08-12 10:25 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    margin-top: 18px;
done

2022-08-12 10:25 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +  margin-bottom: 8px;
done

2022-08-12 10:26 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +  @include for-desktop-up {
done

2022-08-12 10:26 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +  background-color: var(--btn-red-hover-bg-color);
done

2022-08-12 10:26 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +  width: 40px;
done

2022-08-12 10:26 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +  margin-bottom: 70px;
done

2022-08-12 10:26 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +  padding-top: 20px;
done

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk requested changes

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    @include for-phone-only {
тут можно убрать миксин просто оставить font-size и  line-height

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    @include for-tablet-only {
тут замени миксин на for tablet up

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    @include for-phone-only {
тут тоже можно убрать миксин, мы ж потом перезаписываем эти параметры, они и так по умолчанию будут для телефона

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    display: flex;
тут display flex лучше вынести из миксина наверх

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
>      display: flex;
тогда тут можно удалить display flex

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +      padding-right: 63px;
тут нужно добавить font size 16

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +    @include for-phone-only {
этот миксин для телефона можно убрать

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> +      margin: 8px;
объедини эти параметры с миксином на строку выше, они ж одинаковые for-tablet-up

2022-08-12 11:33 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_products.scss
> -.products-list__item--second {
это лучше заменить на селекторы и можно убрать классы модификаторы так как они не нужны
&__item:first-child 
&__item:nth-child(2)  
&__item:last-child

2022-08-12 13:08 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    display: flex;
done

2022-08-12 13:08 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    @include for-phone-only {
done

2022-08-12 13:08 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    @include for-tablet-only {
done

2022-08-12 13:08 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    @include for-phone-only {
done

2022-08-12 13:09 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
>      display: flex;
done

2022-08-12 13:14 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +      padding-right: 63px;
done

2022-08-12 13:15 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    @include for-phone-only {
done

2022-08-12 13:16 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +      margin: 8px;
done

2022-08-12 13:26 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> -.products-list__item--second {
done

2022-08-12 13:30 UTC, Ayzen-Olha commented on src/sass/sections/_products.scss
> +    margin: -16px;
так не вийде. я залишила як є.

2022-08-12 14:09 UTC, Volodymyr-Zastavniuk approved these changes

2022-08-12 14:09 UTC, merged