footer-mobile
Volodymyr-Zastavniuk/team-project-icecream pull request #5
Opened 2022-08-11 16:40 UTC by Ruslan504

набросок мобильной версии футера

2022-08-11 18:31 UTC, Volodymyr-Zastavniuk requested changes

2022-08-11 18:31 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  line-height: 39px;
все line-height желательно перевести в коэффициенты, как на занятиях говорили

2022-08-11 18:31 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  margin-bottom: 56px;
тут маржин 40px (не 56)

2022-08-11 18:31 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  text-align: right;
тут маржин 40пх пропустил

2022-08-11 18:31 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +    <h1>footer</h1>
Заголовок footer нужно скрыть, заменить на h2 и назвать секцию вроде Дополнительная информация. Хотя мне кажется в этой секции заголовок не нужен, это как хочешь. Если оставляешь то h1 надо сменить точно.

2022-08-12 19:04 UTC, Ruslan504 reviewed
готовая секция, прошу просмотреть

2022-08-12 19:09 UTC, Ruslan504 commented on src/partials/footer.html
> +    <h1>footer</h1>
замечания учтены

2022-08-12 19:10 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  text-align: right;
учел

2022-08-12 19:10 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  margin-bottom: 56px;
учел

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk requested changes

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +            <a class="footer__social-link" href="#" target="_blank">
Можно атрибут на ссылку для читалок добавить, пока время есть: aria-label="link to company github page"

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +              <svg class="icon-github">
а на svg для читалок: aria-hidden="true"

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +            <a class="footer__social-link" href="#" target="_blank">
aria-label="link to company telegram page"

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +            <a class="footer__social-link" href="#" target="_blank">
aria-label="link to company facebook page"

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +              <svg class="icon-telegram">
на svg для читалок: aria-hidden="true"

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +              <svg class="icon-facebook">
на svg для читалок: aria-hidden="true"

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/partials/footer.html
> +          <a class="link" href="tel:+61(0)383766284">+61 (0) 383 766 284</a>
на ссылку для читалок aria-label="Company phone number +610383766284"

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +    padding-bottom: 97px;
тут 60пх, 97 это до низа секции

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +    line-height: 1.86;
тут еще появляется в макете letter-spacing: 0.02em; и margin-top: 8px; а маржин боттом пусть везде будет 8пх

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  font-style: normal;
тут добавь margin bottom: 0; а то вылезает марджин 12пх от браузера

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  margin-bottom: 0;
давай маржин боттом 8пх поставим, а то совсем в низ прибивается текст, некрасиво

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  margin-top: 0;
маржин топ тут можно удалить, чуть ниже он повторяется

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  font-family: 'Titan One';
шрифт тут лучше заменить на переменную var(--secondary-font), или дописать семейство cursive

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  font-family: 'Titan One';
шрифт тут лучше заменить на переменную var(--secondary-font), или дописать семейство cursive

2022-08-12 21:10 UTC, Volodymyr-Zastavniuk commented on src/sass/sections/_footer.scss
> +  font-family: 'DM Sans';
тут можно удалить font-family и font-style они от body прилетят.

2022-08-13 11:45 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  font-family: 'DM Sans';
готово

2022-08-13 11:50 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  font-family: 'Titan One';
done

2022-08-13 11:51 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  font-family: 'Titan One';
done

2022-08-13 11:53 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  margin-top: 0;
done

2022-08-13 11:56 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  margin-bottom: 0;
done

2022-08-13 11:59 UTC, Ruslan504 commented on src/partials/footer.html
> +              <svg class="icon-telegram">
done

2022-08-13 12:00 UTC, Ruslan504 commented on src/partials/footer.html
> +              <svg class="icon-github">
done

2022-08-13 12:02 UTC, Ruslan504 commented on src/partials/footer.html
> +            <a class="footer__social-link" href="#" target="_blank">
done

2022-08-13 12:03 UTC, Ruslan504 commented on src/partials/footer.html
> +            <a class="footer__social-link" href="#" target="_blank">
done

2022-08-13 12:03 UTC, Ruslan504 commented on src/partials/footer.html
> +            <a class="footer__social-link" href="#" target="_blank">
done

2022-08-13 12:50 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  line-height: 39px;
done

2022-08-13 12:50 UTC, Ruslan504 commented on src/partials/footer.html
> +              <svg class="icon-facebook">
done

2022-08-13 12:51 UTC, Ruslan504 commented on src/partials/footer.html
> +          <a class="link" href="tel:+61(0)383766284">+61 (0) 383 766 284</a>
done

2022-08-13 12:53 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +    padding-bottom: 97px;
done

2022-08-13 12:56 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +  font-style: normal;
done

2022-08-13 12:59 UTC, Ruslan504 commented on src/sass/sections/_footer.scss
> +    line-height: 1.86;
done

2022-08-13 13:03 UTC, Ruslan504 reviewed
откорректировал с учетом замечаний. Прошу просмотреть

2022-08-13 13:34 UTC, merged